CREATE TABLE IF NOT EXISTS users (
 id CHAR(36) PRIMARY KEY, email VARCHAR(254) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL, metadata JSON NOT NULL,
 created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS sessions (
 token_hash CHAR(64) PRIMARY KEY, user_id CHAR(36) NOT NULL,
 expires_at DATETIME NOT NULL, INDEX(user_id),
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS profiles (
 id CHAR(36) PRIMARY KEY, full_name TEXT, role VARCHAR(50) DEFAULT 'Operator', avatar_url TEXT,
 updated_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
 FOREIGN KEY(id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS slugs (
 slug VARCHAR(100) PRIMARY KEY, resource_id CHAR(36) NOT NULL UNIQUE, kind VARCHAR(10) NOT NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS links (
 id CHAR(36) PRIMARY KEY, user_id CHAR(36) NOT NULL, original_url TEXT NOT NULL,
 short_slug VARCHAR(100) NOT NULL UNIQUE, title TEXT,
 clicks INT UNSIGNED NOT NULL DEFAULT 0, is_archived BOOLEAN NOT NULL DEFAULT FALSE,
 created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), INDEX(user_id, created_at),
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS bio_pages (
 id CHAR(36) PRIMARY KEY, user_id CHAR(36) NOT NULL, slug VARCHAR(100) NOT NULL UNIQUE,
 profile_title TEXT, profile_bio TEXT, theme_settings JSON NOT NULL,
 is_published BOOLEAN NOT NULL DEFAULT TRUE, views INT UNSIGNED NOT NULL DEFAULT 0,
 created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), INDEX(user_id, created_at),
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS traffic_logs (
 id CHAR(36) PRIMARY KEY, user_id CHAR(36) NOT NULL, link_id CHAR(36), bio_page_id CHAR(36),
 type VARCHAR(10) NOT NULL, referrer TEXT, country VARCHAR(10) DEFAULT 'Unknown', device VARCHAR(30), browser VARCHAR(200),
 created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), INDEX(user_id,created_at),
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
 FOREIGN KEY(link_id) REFERENCES links(id) ON DELETE CASCADE,
 FOREIGN KEY(bio_page_id) REFERENCES bio_pages(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS notifications (
 id CHAR(36) PRIMARY KEY, user_id CHAR(36) NOT NULL, type VARCHAR(10), content TEXT NOT NULL,
 is_read BOOLEAN NOT NULL DEFAULT FALSE, created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 INDEX(user_id,created_at), FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS password_setup_tokens (
 token_hash CHAR(64) PRIMARY KEY, user_id CHAR(36) NOT NULL, expires_at DATETIME NOT NULL,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified_at DATETIME(3) NULL;
CREATE TABLE IF NOT EXISTS email_verification_tokens (
 token_hash CHAR(64) PRIMARY KEY, user_id CHAR(36) NOT NULL UNIQUE, expires_at DATETIME NOT NULL,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS mail_outbox (
 id CHAR(36) PRIMARY KEY, user_id CHAR(36) NULL, recipient VARCHAR(254) NOT NULL,
 kind VARCHAR(40) NOT NULL, subject VARCHAR(255) NOT NULL, html_body MEDIUMTEXT NULL, text_body MEDIUMTEXT NULL,
 reply_to VARCHAR(254) NULL, status VARCHAR(20) NOT NULL DEFAULT 'pending', attempts INT NOT NULL DEFAULT 0,
 next_attempt_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, locked_at DATETIME NULL,
 expires_at DATETIME NULL, last_error VARCHAR(100) NULL, sent_at DATETIME NULL,
 created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), INDEX(status,next_attempt_at),
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS contact_messages (
 id CHAR(36) PRIMARY KEY, name VARCHAR(200) NOT NULL, email VARCHAR(254) NOT NULL,
 subject VARCHAR(200) NOT NULL, message TEXT NOT NULL,
 created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB;
